require:
  - rubocop-rspec
  - rubocop-rails

AllCops:                                                                                                                                                                                                                                  
  NewCops: enable